/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TiendaLaModa;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class AgregarProductos extends javax.swing.JFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    
    public AgregarProductos() {
        initComponents();
        connection = DBConnection.ConnectionDB();//Usa el metodo ConnectionDB para establecer conexion...
        //llama la clase DBConnection.java
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cedula = new javax.swing.JLabel();
        Salario = new javax.swing.JLabel();
        Puesto = new javax.swing.JLabel();
        PrecioIngresado = new javax.swing.JTextField();
        ColorIngresado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CodigoIngresado = new javax.swing.JTextField();
        BotonAgregarProductos = new javax.swing.JButton();
        BotonVolverModuloEmpleados = new javax.swing.JButton();
        TipoIngresado = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        CantidadIngresada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cedula.setText("Tipo:");

        Salario.setText("Color:");

        Puesto.setText("Precio:");

        jLabel6.setText("Ingrese los datos del nuevo producto:");

        CodigoIngresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoIngresadoActionPerformed(evt);
            }
        });

        BotonAgregarProductos.setText("Agregar");
        BotonAgregarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarProductosActionPerformed(evt);
            }
        });

        BotonVolverModuloEmpleados.setText("Volver");
        BotonVolverModuloEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverModuloEmpleadosActionPerformed(evt);
            }
        });

        Nombre.setText("Código:");

        jLabel1.setText("Cantidad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre)
                            .addComponent(Cedula)
                            .addComponent(Puesto)
                            .addComponent(Salario)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonVolverModuloEmpleados)
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CodigoIngresado, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(TipoIngresado)
                    .addComponent(PrecioIngresado)
                    .addComponent(ColorIngresado)
                    .addComponent(BotonAgregarProductos)
                    .addComponent(CantidadIngresada))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel6)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cedula))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Puesto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salario)
                    .addComponent(ColorIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantidadIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregarProductos)
                    .addComponent(BotonVolverModuloEmpleados))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CodigoIngresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoIngresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoIngresadoActionPerformed

    private void BotonAgregarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarProductosActionPerformed
        String sql = "INSERT INTO Productos VALUES (?,?,?,?,?)";

        try{

            pst = connection.prepareStatement(sql);
            pst.setString(1, CodigoIngresado.getText());//Se obtiene el valor del campo basado en la variable, no la BD
            pst.setString(2, TipoIngresado.getText());
            pst.setString(3, PrecioIngresado.getText());
            pst.setString(4, ColorIngresado.getText());
            pst.setString(5, CantidadIngresada.getText());
            int resultado = pst.executeUpdate();

            if(resultado == 1){
                JOptionPane.showMessageDialog(null, "Producto agregado exitosamente");

                ModuloProductos newframe = new ModuloProductos();
                newframe.setVisible (true);
                this.dispose();
            }
            pst.close();
            connection.close(); //IMPORTANTE:  Aqui se debe cerrar la base de datos
            // para poder usarla en otro modulo
            //si no se cierra en cada uso, nos da error de bloqueo

        }
        catch (Exception e) {
            System.out.print("Error: " + e.getMessage());

        }
    }//GEN-LAST:event_BotonAgregarProductosActionPerformed

    private void BotonVolverModuloEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverModuloEmpleadosActionPerformed
        ModuloProductos newframe = new ModuloProductos();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonVolverModuloEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarProductos;
    private javax.swing.JButton BotonVolverModuloEmpleados;
    private javax.swing.JTextField CantidadIngresada;
    private javax.swing.JLabel Cedula;
    private javax.swing.JTextField CodigoIngresado;
    private javax.swing.JTextField ColorIngresado;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField PrecioIngresado;
    private javax.swing.JLabel Puesto;
    private javax.swing.JLabel Salario;
    private javax.swing.JTextField TipoIngresado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
