/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TiendaLaModa;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class AgregarProveedores extends javax.swing.JFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    
    public AgregarProveedores() {
        initComponents();
        connection = DBConnection.ConnectionDB();//Usa el metodo ConnectionDB para establecer conexion...
        //llama la clase DBConnection.java
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrimerApellido = new javax.swing.JLabel();
        Cedula = new javax.swing.JLabel();
        Salario = new javax.swing.JLabel();
        Puesto = new javax.swing.JLabel();
        NumeroIngresado = new javax.swing.JTextField();
        TipoProductos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NombreProveedor = new javax.swing.JTextField();
        BotonAgregarProveedor = new javax.swing.JButton();
        NombreEmpresa = new javax.swing.JTextField();
        BotonVolverModuloproveedores = new javax.swing.JButton();
        CedulaJuridicaIngresada = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PrimerApellido.setText("Empresa:");

        Cedula.setText("Cedula juridica:");

        Salario.setText("Tipo de productos:");

        Puesto.setText("Numero de empresa:");

        jLabel6.setText("Ingrese los datos del nuevo proveedor:");

        NombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreProveedorActionPerformed(evt);
            }
        });

        BotonAgregarProveedor.setText("Agregar");
        BotonAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarProveedorActionPerformed(evt);
            }
        });

        NombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEmpresaActionPerformed(evt);
            }
        });

        BotonVolverModuloproveedores.setText("Volver");
        BotonVolverModuloproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverModuloproveedoresActionPerformed(evt);
            }
        });

        CedulaJuridicaIngresada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaJuridicaIngresadaActionPerformed(evt);
            }
        });

        Nombre.setText("Nombre de proveedor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrimerApellido)
                            .addComponent(Nombre)
                            .addComponent(Cedula)
                            .addComponent(Puesto)
                            .addComponent(Salario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonVolverModuloproveedores)
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAgregarProveedor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(NombreProveedor)
                        .addComponent(CedulaJuridicaIngresada)
                        .addComponent(NumeroIngresado)
                        .addComponent(TipoProductos)))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel6)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrimerApellido))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CedulaJuridicaIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumeroIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Puesto))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TipoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salario))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregarProveedor)
                    .addComponent(BotonVolverModuloproveedores))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreProveedorActionPerformed

    private void BotonAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarProveedorActionPerformed
        String sql = "INSERT INTO Proveedores VALUES (?,?,?,?,?)";

        try{
            pst = connection.prepareStatement(sql);
            pst.setString(1, CedulaJuridicaIngresada.getText());//Se obtiene el valor del campo basado en la variable, no la BD
            pst.setString(2, NombreProveedor.getText());
            pst.setString(3, NombreEmpresa.getText());
            pst.setString(4, NumeroIngresado.getText());
            pst.setString(5, TipoProductos.getText());
            int resultado = pst.executeUpdate();

            if(resultado == 1){
                JOptionPane.showMessageDialog(null, "Proveedor agregado exitosamente");

                ModuloProveedores newframe = new ModuloProveedores();
                newframe.setVisible (true);
                this.dispose();
            }
            pst.close();
            connection.close(); //IMPORTANTE:  Aqui se debe cerrar la base de datos
            // para poder usarla en otro modulo
            //si no se cierra en cada uso, nos da error de bloqueo

        }
        catch (Exception e) {
            System.out.print("Error: " + e.getMessage());

        }

    }//GEN-LAST:event_BotonAgregarProveedorActionPerformed

    private void NombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEmpresaActionPerformed

    private void BotonVolverModuloproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverModuloproveedoresActionPerformed
        ModuloProveedores newframe = new ModuloProveedores();
        newframe.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BotonVolverModuloproveedoresActionPerformed

    private void CedulaJuridicaIngresadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaJuridicaIngresadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaJuridicaIngresadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarProveedor;
    private javax.swing.JButton BotonVolverModuloproveedores;
    private javax.swing.JLabel Cedula;
    private javax.swing.JTextField CedulaJuridicaIngresada;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreEmpresa;
    private javax.swing.JTextField NombreProveedor;
    private javax.swing.JTextField NumeroIngresado;
    private javax.swing.JLabel PrimerApellido;
    private javax.swing.JLabel Puesto;
    private javax.swing.JLabel Salario;
    private javax.swing.JTextField TipoProductos;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
