/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TiendaLaModa;
import javax.swing.DefaultListModel;
import java.awt.List;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JOptionPane;

public class BorrarClientes extends javax.swing.JFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private DefaultListModel ClientesModelDL;
    
    public BorrarClientes() {
        initComponents();
        connection = DBConnection.ConnectionDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListaClientes = new javax.swing.JList<>();
        BotonMostrarClientes = new javax.swing.JButton();
        BotonBorrarCliente = new javax.swing.JButton();
        BotonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListaClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaClientes);

        BotonMostrarClientes.setText("Mostrar clientes");
        BotonMostrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarClientesActionPerformed(evt);
            }
        });

        BotonBorrarCliente.setText("Borrar clientes");
        BotonBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarClienteActionPerformed(evt);
            }
        });

        BotonAtras.setText("Atras");
        BotonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(BotonBorrarCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(BotonMostrarClientes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(BotonAtras)))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(BotonMostrarClientes)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonBorrarCliente)
                .addGap(18, 18, 18)
                .addComponent(BotonAtras)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMostrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarClientesActionPerformed
        String sql = "SELECT * FROM Clientes";
        ClientesModelDL = new DefaultListModel();
        ListaClientes.setModel(ClientesModelDL);

        try{
            String Cedula, Nombre, Celular, Residencia;
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();

            while  (rs.next()) {

                Cedula = rs.getString("Cedula");
                Nombre = rs.getString("Nombre");
                Celular = rs.getString("Celular");
                Residencia = rs.getString("Residencia");
                

                String ClientesAll = Cedula + "/" + Nombre + "/" + Celular + "/" + Residencia;
                ClientesModelDL.addElement(ClientesAll);

            }
            //rs.close();
            //connection.close();

        }catch (Exception e){

        }

    }//GEN-LAST:event_BotonMostrarClientesActionPerformed

    private void BotonBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarClienteActionPerformed
        String sql = "DELETE FROM Clientes WHERE Cedula = ?";
        //EmpleadosModelDL = new DefaultListModel();
        //ListaEmpleados.setModel(EmpleadosModelDL);

        try{

            int index = ListaClientes.getSelectedIndex();
            String s = (String) ListaClientes.getSelectedValue();
            String[] parts = s.split("/");
            String Cedula = parts[0];
            System.out.print(Cedula);

            pst = connection.prepareStatement(sql);
            pst.setString(1, Cedula);
            int resultado = pst.executeUpdate();
            //rs.close();
            //connection.close();

        }catch (Exception e){

        }

        BotonMostrarClientesActionPerformed(evt);

    }//GEN-LAST:event_BotonBorrarClienteActionPerformed

    private void BotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasActionPerformed
        ModuloClientes newframe = new ModuloClientes();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtras;
    private javax.swing.JButton BotonBorrarCliente;
    private javax.swing.JButton BotonMostrarClientes;
    private javax.swing.JList<String> ListaClientes;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
