/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TiendaLaModa;

import javax.swing.DefaultListModel;
import java.awt.List;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JOptionPane;

public class BorrarProveedores extends javax.swing.JFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private DefaultListModel ProveedoresModelDL;
    
    public BorrarProveedores() {
        initComponents();
        connection = DBConnection.ConnectionDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListaProveedores = new javax.swing.JList<>();
        BotonMostrarProveedores = new javax.swing.JButton();
        BotonBorrarProveedor = new javax.swing.JButton();
        BotonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListaProveedores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaProveedores);

        BotonMostrarProveedores.setText("Mostrar proveedores");
        BotonMostrarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarProveedoresActionPerformed(evt);
            }
        });

        BotonBorrarProveedor.setText("Borrar proveedores");
        BotonBorrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarProveedorActionPerformed(evt);
            }
        });

        BotonAtras.setText("Atras");
        BotonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonBorrarProveedor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonMostrarProveedores, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotonAtras)
                        .addGap(41, 41, 41)))
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(BotonMostrarProveedores)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(BotonBorrarProveedor)
                .addGap(18, 18, 18)
                .addComponent(BotonAtras)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMostrarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarProveedoresActionPerformed
        String sql = "SELECT * FROM Proveedores";
        ProveedoresModelDL = new DefaultListModel();
        ListaProveedores.setModel(ProveedoresModelDL);

        try{
            String CedulaJuridica, NombreProveedor, Empresa, Numero, TipoProductos;
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();

            while  (rs.next()) {

                CedulaJuridica = rs.getString("CedulaJuridica");
                NombreProveedor = rs.getString("NombreProveedor");
                Empresa = rs.getString("Empresa");
                Numero = rs.getString("Numero");
                TipoProductos = rs.getString("TipoProductos");

                String ProveedoresAll = CedulaJuridica + "/" + NombreProveedor + "/" + Empresa + "/" + Numero + "/" + TipoProductos;
                ProveedoresModelDL.addElement(ProveedoresAll);

            }
            //rs.close();
            //connection.close();

        }catch (Exception e){

        }
    }//GEN-LAST:event_BotonMostrarProveedoresActionPerformed

    private void BotonBorrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarProveedorActionPerformed
        String sql = "DELETE FROM Proveedores WHERE CedulaJuridica = ?";
        //EmpleadosModelDL = new DefaultListModel();
        //ListaEmpleados.setModel(EmpleadosModelDL);

        try{

            int index = ListaProveedores.getSelectedIndex();
            String s = (String) ListaProveedores.getSelectedValue();
            String[] parts = s.split("/");
            String Cedula = parts[0];
            System.out.print(Cedula);

            pst = connection.prepareStatement(sql);
            pst.setString(1, Cedula);
            int resultado = pst.executeUpdate();
            //rs.close();
            //connection.close();

        }catch (Exception e){

        }

        BotonMostrarProveedoresActionPerformed(evt);
    }//GEN-LAST:event_BotonBorrarProveedorActionPerformed

    private void BotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasActionPerformed
        ModuloProveedores newframe = new ModuloProveedores();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrarProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtras;
    private javax.swing.JButton BotonBorrarProveedor;
    private javax.swing.JButton BotonMostrarProveedores;
    private javax.swing.JList<String> ListaProveedores;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
