/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TiendaLaModa;
import javax.swing.DefaultListModel;
import java.awt.List;
import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;  
import java.util.Random
/**
 *
 * @author tifanycantillo
 */
public class IngresarVenta extends javax.swing.JFrame {
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private DefaultListModel VentasModelDL;
    
    /**
     * Creates new form IngresarVenta
     */
    public IngresarVenta() {
        initComponents();
        connection = DBConnection.ConnectionDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jFrame1 = new javax.swing.JFrame();
        ButtonMostrarVentas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaProductos = new javax.swing.JList<>();
        BotonAgregar = new javax.swing.JButton();
        SelectEfectivo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        SelectTarjeta = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxComprador = new javax.swing.JComboBox<>();
        ComboBoxVendedor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        BotonAtras = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonMostrarVentas.setText("Mostrar Productos");
        ButtonMostrarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMostrarVentasActionPerformed(evt);
            }
        });

        jLabel1.setText("Por favor seleccione los productos que desea comprar");

        ListaProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListaProductos);

        BotonAgregar.setText("Agregar");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        SelectEfectivo.setText("Efectivo");
        SelectEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectEfectivoActionPerformed(evt);
            }
        });

        jLabel2.setText("Por favor seleccione el metodo de pago");

        SelectTarjeta.setText("Tarjeta");

        jLabel3.setText("Comprador");

        ComboBoxComprador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBoxCompradorMouseClicked(evt);
            }
        });
        ComboBoxComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCompradorActionPerformed(evt);
            }
        });

        ComboBoxVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        ComboBoxVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxVendedorActionPerformed(evt);
            }
        });

        jLabel5.setText("Vendedor");

        BotonAtras.setText("Atras");
        BotonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonMostrarVentas)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(SelectEfectivo)
                            .addComponent(SelectTarjeta))))
                .addGap(0, 123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ButtonMostrarVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(SelectEfectivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelectTarjeta)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregar)
                    .addComponent(BotonAtras))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMostrarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMostrarVentasActionPerformed
        ListaProductos.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        
        String sql = "SELECT * FROM Productos";
        VentasModelDL = new DefaultListModel();
        ListaProductos.setModel(VentasModelDL);
        
        try{
            String Codigo, Tipo, Precio, Color;
            int Cantidad;
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                Codigo = rs.getString("Codigo");
                Tipo = rs.getString("Tipo");
                Precio = rs.getString("Precio");
                Color = rs.getString("Color");
                Cantidad = rs.getInt("Cantidad");
                
                String ProductosAll = Tipo + "/" + "Precio: " + Precio + "/" + "Color: " + Color + "/" + "Cantidad: " + String.valueOf(Cantidad);
                VentasModelDL.addElement(ProductosAll);
            }
        }catch(Exception e){
        
        }
        
        // Popular Clientes y Vendedores cuando se despliegan los productos.
           String sql2 = "SELECT Nombre FROM Clientes ";
        
        try{
            pst = connection.prepareStatement(sql2);
            rs = pst.executeQuery();
            
            while (rs.next()){
                String nombre = rs.getString("Nombre");
                ComboBoxComprador.addItem(nombre);
            }
            
            //connection.close();
            
        } catch (Exception e) {
        
        }
        
        // Popular Vendedores cuando se despliegan los productos
        
          String sql3 = "SELECT Empresa FROM Proveedores";
        
        try{
            pst = connection.prepareStatement(sql3);
            rs = pst.executeQuery();
            
            while (rs.next()){
                String nombre = rs.getString("Empresa");
                ComboBoxVendedor.addItem(nombre);
            }
            
            //connection.close();
            
        } catch (Exception e) {
        
        }
        
    }//GEN-LAST:event_ButtonMostrarVentasActionPerformed

    private void SelectEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectEfectivoActionPerformed

    private void BotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasActionPerformed
        ModuloVentas newframe = new ModuloVentas();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonAtrasActionPerformed

    private void ComboBoxCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCompradorActionPerformed
        
    }//GEN-LAST:event_ComboBoxCompradorActionPerformed

    private void ComboBoxVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxVendedorActionPerformed

    private void ComboBoxCompradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxCompradorMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ComboBoxCompradorMouseClicked

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        // TODO add your handling code here:
        //ListaProductos.getSelectionModel().addSelectionInterval(0, 100);
        //ListaProductos.setSelectedIndices(new int[] { 0, 2 });
        //int index = ListaProductos.getSelectedIndex()
        
        /* LISTA */
        java.util.List<String> list = ListaProductos.getSelectedValuesList();
        //int[] indeces = ListaProductos.getSelectedIndices();
        //String producto = (String) ListaProductos.getSelectedValue();
        
        java.util.List<String> productos = new ArrayList();
        
        for(int i = 0; i<list.size(); i++){
            String item = list.get(i);
            String[] producto_list = item.split("/");
            productos.add(producto_list[0]);
            
        }
        
        /* METODO DE PAGO */
        
        String metodo = "";
        
        if (SelectEfectivo.isSelected()){
            metodo = SelectEfectivo.getText();
        }else if (SelectTarjeta.isSelected()){
            metodo = SelectTarjeta.getText();
        }
        
        // METER "metodo" en la tabla.
        
        //JOptionPane.showMessageDialog(null, metodo);
        /* COMPRADOR */
        String Comprador = ComboBoxComprador.getSelectedItem().toString();
        
        /* VENDEDOR */
        String Vendedor = ComboBoxVendedor.getSelectedItem().toString();
        
        /* GENERAR FECHA DE HOY PARA LA BASE DE DATOS */
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now();  
        
        String fecha = dtf.format(now);
   
       
        JOptionPane.showMessageDialog(null, productos);
        JOptionPane.showMessageDialog(null, metodo);
        JOptionPane.showMessageDialog(null, Comprador);
        JOptionPane.showMessageDialog(null, Vendedor);
        JOptionPane.showMessageDialog(null, fecha);
        
        
        String sql = "INSERT INTO Ventas VALUES (?,?,?,?,?,?)";

        try{
            pst = connection.prepareStatement(sql);
            
            String listString = String.join(", ", productos);
            Random rand = new Random();
            int random = rand.nextInt(1000000);
            pst.setString(1, String.valueOf(random));
            pst.setString(2, listString);
            pst.setString(3, fecha);
            pst.setString(4, metodo);
            pst.setString(5, Comprador);
            pst.setString(6, Vendedor);
            int resultado = pst.executeUpdate();

            if(resultado == 1){
                JOptionPane.showMessageDialog(null, "Venta agregado exitosamente");

                ModuloVentas newframe = new ModuloVentas();
                newframe.setVisible (true);
                this.dispose();
            }
            pst.close();
            connection.close(); //IMPORTANTE:  Aqui se debe cerrar la base de datos
            // para poder usarla en otro modulo
            //si no se cierra en cada uso, nos da error de bloqueo

        }
        catch (Exception e) {
            System.out.print("Error: " + e.getMessage());

        }
        
        //JOptionPane.showMessageDialog(null, producto);
        //JOptionPane.showMessageDialog(null, list);
        
        // CREAR UN INSERT EN LA BASE DE DATOS CON TODOS LOS CAMPOS/VARIABLES CORRESPONDIENTES HASTA EL MOMENTO
        // A LA VEZ, ITERAR CON UN FOR POR LOS PRODUCTOS YA QUE UN USUARIO PUEDE SELECCIONAR VARIOS.
        
        
    }//GEN-LAST:event_BotonAgregarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonAtras;
    private javax.swing.JButton ButtonMostrarVentas;
    private javax.swing.JComboBox<String> ComboBoxComprador;
    private javax.swing.JComboBox<String> ComboBoxVendedor;
    private javax.swing.JList<String> ListaProductos;
    private javax.swing.JRadioButton SelectEfectivo;
    private javax.swing.JRadioButton SelectTarjeta;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
